src/main/java/kr/kernel360/anabada/domain/faq/api/FaqController.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/CreateFaqRequest.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/CreateFaqResponse.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqDto.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqResponse.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqResponse.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/UpdateFaqRequest.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/UpdateFaqResponse.java
src/main/java/kr/kernel360/anabada/domain/faq/entity/Faq.java
src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java

* Faq 엔티티를 수정하였습니다.
* FaqController에 crud를 위한 메서드를 추가하였습니다.
* FaqService에 crud를 위한 메서드를 추가하였습니다.
* crud 기능을 위한 request, response dto를 추가하였습니다.
* 코드리뷰 반영하여 수정

feat : faq crud 기능

---

src/main/resources/static/trade/tradeCreateForm.html

feat: 교환 등록 화면

---

src/main/resources/static/faq/faqCreateForm.html
src/main/resources/static/faq/faqInfo.html
src/main/resources/static/faq/faqList.html
src/main/resources/static/faq/faqUpdateForm.html

feat : faq 화면

---

src/main/java/kr/kernel360/anabada/domain/category/dto/CreateCategoryRequest.java
src/main/java/kr/kernel360/anabada/domain/category/dto/FindCategoryResponse.java
src/main/java/kr/kernel360/anabada/domain/category/entity/Category.java
src/main/java/kr/kernel360/anabada/domain/comment/api/CommentController.java
src/main/java/kr/kernel360/anabada/domain/comment/dto/CreateCommentRequest.java
src/main/java/kr/kernel360/anabada/domain/comment/dto/FindAllCommentDto.java
src/main/java/kr/kernel360/anabada/domain/comment/dto/FindAllCommentResponse.java
src/main/java/kr/kernel360/anabada/domain/comment/entity/Comment.java
src/main/java/kr/kernel360/anabada/domain/comment/repository/CommentRepository.java
src/main/java/kr/kernel360/anabada/domain/comment/service/CommentService.java
src/main/java/kr/kernel360/anabada/domain/trade/dto/CreateTradeRequest.java
src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
src/main/java/kr/kernel360/anabada/global/commons/domain/DeletedStatus.java
src/main/resources/application.yml

* ``CommentController``, ``CommentService``에 create, findall 추가
* ``Trade``, ``TradeOffer`` 에 ``DeletedStatus`` 추가
* enum type ``DeletedStatus`` 추가

feat : 댓글 추가, 목록 조회 기능 구현 및 ERD 추가 내용 수정

---

src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberResponse.java
src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/CreateTradeOfferRequest.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferRequest.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferResponse.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferDto.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/UpdateTradeOfferRequest.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/UpdateTradeOfferResponse.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepository.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java

* ``TradeOfferController``, ``TradeOfferService``에 create, update
*  ``TradeOffer``에 ``TradeOfferStatus``
*  enum type ``TradeOfferStatus``

feat : 교환 요청 추가, 수정

---

src/main/java/kr/kernel360/anabada/global/api/KakaoFeignController.java
src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
src/main/resources/static/auth/login.html
src/main/resources/static/include/footer.html
src/main/resources/static/include/header.html
src/main/resources/static/index.html
src/main/resources/static/main.html

- footer의 저작권 문구를 삭제했습니다.
- index화면과 main 화면을 분리했습니다.
- main 화면 서비스소개 문구를 수정했습니다.
- main화면 접근 시 현재 접속 위치가 header에 표시되도록 수정했습니다.
- 현재 접속 위치를 로컬스토리지에 json형태로 저장하도록 수정했습니다.

refactor : 메인화면 접속위치 수정

---

src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
src/main/java/kr/kernel360/anabada/domain/category/dto/FindAllCategoryResponse.java
src/main/java/kr/kernel360/anabada/domain/category/entity/Category.java
src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqResponse.java
src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
src/main/resources/static/category/categoryList.html
src/main/resources/static/main.html

* category 목록 조회 기능을 추가했습니다. 
* 카테고리 목록 조회 기능 추가
*  카테고리 삭제 시 비활성화 되고 다시 버튼을 누르면 활성화로 변경됩니다. 
* 현재 카테고리 들어가는 링크가 서비스 소개 페이지에 들어있어 차후 수정이 필요합니다.
* 카테고리 수정 기능을 추후 사용하지 않을 예정이므로 삭제하였습니다.

feat : 카테고리 화면 추가

---

src/main/resources/static/auth/signup.html

회원가입 시 성별을 여성으로 선택해도 남성으로만 등록되고 있는 현상을 개선하였습니다.

bug : 회원가입 성별선택 버그 수정

---

src/main/resources/static/auth/signup.html
src/main/resources/static/chart/adminChart.html

feat : 관리자 통계 스타일 수정

---

src/main/resources/static/index.html
src/main/resources/static/trade/tradeInfo.html
src/main/resources/static/trade/tradeRequestForm.html

- 교환 상세페이지에서 거래 요청 화면으로 이동할 때 필요한 데이터를 담아 전달하도록 추가했습니다.
- 거래요청 화면을 생성했습니다. 서버 쪽과 연결이 필요합니다.

feat : 거래 요청 화면

---

src/main/java/kr/kernel360/anabada/domain/faq/dto/CreateFaqRequest.java
src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
src/main/resources/static/faq/faqCreateForm.html

- 회원 정보를 포함하여 저장해야하는 경우 jwt 페이로드의 이메일을 가져와 회원 식별자로 사용하여 회원정보를 포함하여 등록할 수 있도록 수정하였습니다.
-  images/trade, images/tradeOffer 디렉터리를 추가하였습니다.

refactor : 회원 식별자 jwt에서 가져오도록 수정, 이미지 디렉터리 추가

---

src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginRequest.java
src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginResponse.java
src/main/java/kr/kernel360/anabada/domain/auth/dto/TokenDto.java
src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
src/main/java/kr/kernel360/anabada/global/client/KakaoClient.java
src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
src/main/resources/static/member/memberInfo.html
src/main/resources/static/trade/tradeCreateForm.html

* my page에 교환 요청 화면 추가
* class에 공백 안들어가있던 것들 삽입

feat : my page 교환 요청 추가

---

src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
src/main/resources/static/trade/tradeCreateForm.html
src/main/resources/static/trade/tradeList.html

- 교환 등록 페이지의 하드코딩 되어있던 카테고리 목록을 제거하고 등록된 카테고리 중 활성화된 카테고리 목록을 조회하도록 구현하였습니다.
- 교환 목록의 거래유형에 뱃지 스타일을 적용하였습니다.

feat : 교환 등록의 카테고리 목록 조회 및 교환 목록 거래유형 뱃지 적용

---

src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeDto.java
src/main/java/kr/kernel360/anabada/domain/trade/dto/TradeSearchCondition.java
src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
src/main/java/kr/kernel360/anabada/global/config/QuerydslConfig.java
src/main/resources/static/trade/tradeList.html

- QuerydslConfig을 생성하고 JPAQueryFactory를 빈으로 등록하였습니다.
- 교환 목록 페이징 기능을 구현했습니다.
- 교환 목록 검색 기능을 구현했습니다.
- 교환조회 카테고리 검색 시 count 쿼리에서 카테고리 테이블을 조인하지 않도록 수정했습니다.

feat : 교환목록 페이징, 검색 기능, 검색 count 쿼리 성능 최적화

---

src/main/java/kr/kernel360/anabada/domain/faq/api/FaqController.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/FaqSearchCondition.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqResponse.java
src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepositoryCustom.java
src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepositoryImpl.java
src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
src/main/java/kr/kernel360/anabada/global/client/KakaoClient.java
src/main/java/kr/kernel360/anabada/global/config/KakaoFeignConfig.java
src/main/resources/static/faq/faqList.html
src/main/resources/static/trade/tradeList.html

- FAQ 목록 페이징 및 검색 기능을 구현했습니다.
- 교환 목록 페이징 오류를 수정하였습니다.
- kakaoFeignConfiguration -> kakaoFeignConfig 클래스 명을 수정하였습니다.

feat : FAQ 페이징, 검색 기능 구현

---

.gitignore
src/main/resources/logback-spring.xml

- logs/ 파일에 로그파일이 저장되도록 logback-spring.xml 파일을 설정했습니다.
- .gitignore 파일에 logs/ 파일을 추가했습니다.
aop를 사용하여 로그파일을 어떻게 저장할지 추후 결정이 필요합니다.

feat : logback 추가

---

src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
src/main/resources/static/faq/faqList.html
src/main/resources/static/index.html

- 관리자 페이지에서 호출되는 API를 토큰정보에 관리권한이 있어야 접근 가능하도록 구현하였습니다.
- FAQ 등록 버튼을 관리자권한을 가지고 있는 사용자만 확인할 수 있도록 구현하였습니다.

feat : 관리자 API 접근 권한 설정

---

src/main/resources/static/index.html
src/main/resources/static/member/memberInfo.html
src/main/resources/static/trade/tradeCreateForm.html
src/main/resources/static/trade/tradeInfo.html
src/main/resources/static/trade/tradeList.html
src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
src/main/resources/static/tradeOffer/tradeOfferInfo.html
src/main/resources/static/tradeOffer/tradeOfferList.html

- javascript에서 불필요한 로그를 삭제했습니다.

chore : remove console log

---

src/main/resources/static/faq/faqInfo.html
src/main/resources/static/index.html

* 위치정보 캐시에 저장해서 사용할 수 있도록 수정
* Faq 수정 삭제 버튼 관리자에게만 보이도록 수정

refactor : 위치 정보 캐시 적용, faq 수정 삭제 버튼 수정

---

src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
src/main/java/kr/kernel360/anabada/global/FileHandler.java
src/main/java/kr/kernel360/anabada/global/error/code/FileErrorCode.java
src/main/resources/static/index.html

- 새로고침 시 위치정보 및 사용자정보 누락되는 현상을 수정하였습니다.
- 거래요청 목록에서 거래요청 작성자 닉네임이 교환 본문 글 작성자 닉네임으로 잘못 출력되는 현상을 수정하였습니다.
- 파일처리 소스를 리팩토링 하였습니다.

bug :  버그 테스트 발견 버그 수정 및 리팩토링

---

src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java

- 교환목록, 교환요청목록 정렬 조건을 날짜순 + 상태순으로 수정했습니다.

fix : 교환목록, 교환요청목록 정렬 조건

---

src/test/java/kr/kernel360/anabada/domain/category/service/CategoryServiceTest.java

feat: categoryServiceTest 추가
